import { useEffect, useRef, useState } from 'react';
import { BookOpen, Users, Church, FolderOpen, ShieldCheck, LogOut, Search, Plus, ArrowUpRight, ArrowLeft, Clock3, MapPin, Camera, FileText, Upload, Pencil, LockKeyhole, Info, Check, UserRound, ChevronRight, RefreshCw, X } from 'lucide-react';
import { Button, Input, Label, Badge, Checkbox, Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose, Tabs, TabsList, TabsTrigger, TabsContent, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Sidebar, SidebarProvider, SidebarContent, SidebarHeader, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, SidebarTrigger, useSidebar, Skeleton, Empty, EmptyHeader, EmptyTitle, EmptyDescription, EmptyMedia, Toaster } from './components/ui.jsx';
import { toast } from 'sonner';

const roleNames = {admin:'Administración',catechist:'Catequista',reader:'Consulta · arzobispado'};
const itineraries = {'confirmation':'Confirmación','baptism-1':'Bautismo y comunión · 1.º','baptism-2':'Bautismo y comunión · 2.º'};
const docNames = {birth:'Partida de nacimiento',baptism:'Certificado de bautismo','sponsor-confirmation':'Confirmación del padrino / madrina',registration:'Ficha de inscripción'};
const statuses = {yes:'Sí',no:'No',unknown:'Sin comprobar'};
const fields = [['birthDate','Fecha de nacimiento','date'],['birthPlace','Lugar de nacimiento'],['phone','Teléfono','tel'],['email','Correo electrónico','email'],['address','Domicilio'],['city','Localidad'],['province','Provincia'],['postalCode','Código postal'],['country','País']];
const family = [['father','Padre'],['mother','Madre'],['paternalGrandfather','Abuelo paterno'],['paternalGrandmother','Abuela paterna'],['maternalGrandfather','Abuelo materno'],['maternalGrandmother','Abuela materna']];
const clean = (value) => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const date = (value) => value ? new Date(value.length===10?`${value}T12:00:00`:value).toLocaleDateString('es-ES',{day:'numeric',month:'short',year:'numeric'}) : 'Sin indicar';
function Choice({label,value,onChange,options,id,disabled=false}) {
  return <div className="field"><Label htmlFor={id}>{label}</Label><select id={id} className="input" value={value} onChange={event=>onChange(event.target.value)} disabled={disabled}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div>;
}
function Fact({label,children}) {return <div className="fact"><dt>{label}</dt><dd>{children || <span className="muted">Sin indicar</span>}</dd></div>;}
function Avatar({person,large=false}) {return <div className={`person-avatar ${large?'large':''}`}>{person.photoId?<img src={`/api/files/${person.photoId}`} alt={`Foto de ${person.firstName}`}/>:<span>{person.firstName[0]}{person.lastName[0]}</span>}</div>;}
function NoResults({title,description}) {return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><FolderOpen/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>;}
function Navigation({view,onView,user,onLogout}) {
  const {setOpenMobile}=useSidebar();
  const items=[{id:'people',name:user.role==='admin'?'Personas y asignaciones':'Personas',icon:Users},{id:'groups',name:'Grupos',icon:Church},...(user.role==='admin'?[{id:'users',name:'Usuarios',icon:ShieldCheck}]:[]),{id:'guide',name:'Guía de esta versión',icon:BookOpen}];
  return <Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span className="brand-mark"><BookOpen size={25}/></span><div>Catequesis<small>DE ADULTOS</small></div></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>ESPACIO DE GESTIÓN</SidebarGroupLabel><SidebarMenu>{items.map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton isActive={view===item.id} onClick={()=>{onView(item.id);setOpenMobile(false);}} className="nav-item"><item.icon/><span>{item.name}</span>{view===item.id&&<ChevronRight className="ml-auto"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><div className="sidebar-note"><span className="small-line"/><p>La información de cada persona,<br/>en su lugar.</p><small>Solo gestión y consulta documental.</small></div></SidebarContent><SidebarFooter><div className="account"><span className="account-icon"><UserRound size={18}/></span><div><strong>{user.name.split(' · ')[0]}</strong><small>{roleNames[user.role]}</small></div></div><Button variant="ghost" onClick={onLogout} className="logout"><LogOut size={16}/>Cerrar sesión</Button><div className="sidebar-version">VERSIÓN 0.1 · LOCAL</div></SidebarFooter></Sidebar>;
}

export default function CatequesisApp() {
  const [session,setSession]=useState(null),csrf=useRef('');
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [people,setPeople]=useState([]),[groups,setGroups]=useState([]),[users,setUsers]=useState([]);
  const [view,setView]=useState('people'),[selected,setSelected]=useState(null),[modal,setModal]=useState(null);
  const [query,setQuery]=useState(''),[groupFilter,setGroupFilter]=useState('all');
  const [loginName,setLoginName]=useState('ana'),[loginPassword,setLoginPassword]=useState(''),[available,setAvailable]=useState(false);
  const api=async(path,method='GET',data)=>{
    const res=await fetch(path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf.current},body:data===undefined?undefined:JSON.stringify(data)});
    let value;try{value=await res.json();}catch{throw new Error('El servidor local no ha devuelto una respuesta válida.');}
    if(!res.ok){
      if(res.status===401&&path!=='/api/login'&&path!=='/api/session'){setSession(null);setPeople([]);setUsers([]);setGroups([]);setSelected(null);setModal(null);csrf.current='';}
      throw new Error(value.error||'No se ha podido completar la solicitud.');
    }
    return value;
  };
  async function load(user, keepId){const [ps,gs,us]=await Promise.all([api('/api/people'),api('/api/groups'),user.role==='admin'?api('/api/users'):Promise.resolve([])]);setPeople(ps);setGroups(gs);setUsers(us);if(keepId)setSelected(ps.find(p=>p.id===keepId)??null);}
  useEffect(()=>{
    let live=true;
    (async()=>{try{await api('/api/meta');if(!live)return;setAvailable(true);try{const s=await api('/api/session');if(!live)return;csrf.current=s.csrf;setSession(s);await load(s.user);}catch{/* Not signed in. */}}catch{if(live)setError('El servidor local no responde. Arranca la aplicación siguiendo README.md.');}finally{if(live)setLoading(false);}})();
    return()=>{live=false;};
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  async function login(event){event.preventDefault();setBusy(true);setError('');try{const s=await api('/api/login','POST',{username:loginName,password:loginPassword});csrf.current=s.csrf;setSession(s);setLoginPassword('');setView('people');setQuery('');setGroupFilter('all');await load(s.user);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{await api('/api/logout','POST',{});setSession(null);setSelected(null);setModal(null);setPeople([]);setGroups([]);setUsers([]);csrf.current='';setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function refresh(){if(!session)return;setBusy(true);setError('');try{await load(session.user,selected?.id);toast.success('Información actualizada');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function openPerson(p){setError('');try{setSelected(await api(`/api/people/${p.id}`));}catch(e){setError(e.message);}}
  async function saved(){if(!session)return;await load(session.user,selected?.id);setModal(null);toast.success('Cambios guardados en este ordenador');}
  function changeView(v){setView(v);setSelected(null);setError('');}
  const isAdmin=session?.user.role==='admin';
  if(loading)return <main className="boot"><BookOpen size={32}/><h1>Catequesis de adultos</h1><p>Preparando tu espacio…</p><Skeleton className="h-3 w-52"/></main>;
  if(!session)return <main className="login-page"><section className="login-story"><div className="brand"><span className="brand-mark"><BookOpen size={28}/></span><div>Catequesis<small>DE ADULTOS</small></div></div><div className="login-intro"><p className="eyebrow">UN ESPACIO PARA ACOMPAÑAR</p><h1>Cada persona.<br/>Su historia.<br/><em>Su camino.</em></h1><p>Fichas, grupos y documentos reunidos para consultar la información con calma.</p></div><div className="login-footer"><span>PRIMERA VERSIÓN</span><span>01 / GESTIÓN LOCAL</span></div></section><section className="login-panel"><div className="login-card"><Badge variant="outline" className="demo-badge"><span className="status-dot"/>Demostración · datos ficticios</Badge><h2>Entrar en catequesis</h2><p className="muted">Elige un perfil de prueba para recorrer la aplicación.</p><form onSubmit={login} className="login-form"><div className="field"><Label htmlFor="username">Usuario</Label><Input id="username" autoComplete="username" required value={loginName} onChange={e=>setLoginName(e.target.value)}/></div><div className="field"><Label htmlFor="password">Contraseña</Label><Input id="password" type="password" autoComplete="current-password" required value={loginPassword} onChange={e=>setLoginPassword(e.target.value)}/></div>{error&&<div role="alert" className="error-box">{error}</div>}<Button type="submit" size="lg" className="login-submit" disabled={busy||!available}>{busy?'Entrando…':'Entrar en la aplicación'}<ArrowUpRight size={18}/></Button></form><div className="demo-credentials"><strong>Accesos de prueba</strong><div className="profile-picks">{[['ana','Catequista · Ana'],['luis','Catequista · Luis'],['admin','Administración'],['consulta','Arzobispado']].map(([v,t])=><Button key={v} variant="outline" size="sm" onClick={()=>{setLoginName(v);setLoginPassword('Catequesis-demo-2026!');}}>{t}</Button>)}</div><p>Contraseña común: <code>Catequesis-demo-2026!</code></p><small>Estas cuentas son solo para esta demostración local. No uses información real ni publiques el servidor.</small></div></div><p className="login-bottom"><LockKeyhole size={14}/>La sesión y los permisos se comprueban en el servidor.</p></section></main>;
  return <SidebarProvider><Navigation view={view} onView={changeView} user={session.user} onLogout={logout}/><SidebarInset className="workspace"><header className="topbar"><div className="topbar-left"><SidebarTrigger aria-label="Mostrar u ocultar navegación"/><span className="crumb">Catequesis de adultos<span>/</span>{view==='people'?'Personas':view==='groups'?'Grupos':view==='users'?'Usuarios':'Guía'}</span></div><div className="topbar-right"><span className="local-status"><span className="status-dot"/>En este ordenador</span><Badge variant="outline">{roleNames[session.user.role]}</Badge></div></header><div className="demo-strip"><Info size={15}/><span>Versión de revisión. Nombres ficticios y archivos de prueba.</span></div><main className="main-content" id="contenido">{error&&<div role="alert" className="error-box page-error">{error}<Button variant="ghost" size="sm" onClick={()=>setError('')} aria-label="Cerrar aviso"><X size={16}/></Button></div>}
    {view==='people'&&(selected?<PersonDetail person={selected} group={groups.find(g=>g.id===selected.groupId)} canEdit={session.user.role==='catechist'} onBack={()=>setSelected(null)} onModal={setModal}/>:<PeopleList people={people} groups={groups} users={users} isAdmin={isAdmin} query={query} onQuery={setQuery} groupFilter={groupFilter} onGroupFilter={setGroupFilter} onRefresh={refresh} busy={busy} onOpen={openPerson} onModal={setModal}/>)}
    {view==='groups'&&<GroupsView groups={groups} isAdmin={isAdmin} onModal={setModal} onPeople={id=>{setGroupFilter(id);setQuery('');changeView('people');}}/>}
    {view==='users'&&isAdmin&&<UsersView users={users} groups={groups} onModal={setModal}/>}
    {view==='guide'&&<Guide/>}
    </main><footer className="workspace-footer"><span>Catequesis de adultos</span><span>Primera entrega · 0.1.0 · Solo para revisión</span></footer></SidebarInset>{modal&&<EditModal modal={modal} groups={groups} users={users} api={api} onClose={()=>setModal(null)} onSaved={saved}/>}<Toaster position="bottom-right" theme="light" richColors/></SidebarProvider>;
}

function PeopleList({people,groups,users,isAdmin,query,onQuery,groupFilter,onGroupFilter,onRefresh,busy,onOpen,onModal}) {
  const filtered=people.filter(p=>(groupFilter==='all'||p.groupId===groupFilter)&&clean(`${p.firstName} ${p.lastName} ${p.data?.email??''}`).includes(clean(query)));
  const findGroup=(id)=>groups.find(g=>g.id===id);
  const docCount=people.reduce((n,p)=>n+(p.documents?.length??0),0);
  return <><div className="page-heading"><div><p className="eyebrow">{isAdmin?'ORGANIZACIÓN':'TU ESPACIO DE ACOMPAÑAMIENTO'}</p><h1>{isAdmin?'Personas y asignaciones':'Personas en catequesis'}</h1><p>{isAdmin?'Altas mínimas y un único grupo activo por persona.':'Consulta sus fichas y ten a mano la documentación.'}</p></div><div className="heading-actions"><Button variant="outline" onClick={onRefresh} disabled={busy}><RefreshCw size={16}/>Actualizar</Button>{isAdmin&&<Button onClick={()=>onModal({kind:'person'})}><Plus size={16}/>Nueva ficha</Button>}</div></div>
  {isAdmin&&<div className="permission-note"><ShieldCheck size={18}/><p>Solo nombre y grupo para organizar las asignaciones. Los datos personales ampliados y los archivos quedan fuera del acceso de administración.</p></div>}
  <div className="summary-row"><div className="summary-cell"><span className="summary-icon"><Users size={19}/></span><div><strong>{people.length}</strong><span>{isAdmin?'personas registradas':'personas en tu ámbito'}</span></div></div><div className="summary-cell"><span className="summary-icon"><Church size={19}/></span><div><strong>{groups.length}</strong><span>{isAdmin?'grupos organizados':'grupos asignados'}</span></div></div><div className="summary-cell"><span className="summary-icon">{isAdmin?<ShieldCheck size={19}/>:<FolderOpen size={19}/>}</span><div><strong>{isAdmin?users.filter(u=>u.active).length:docCount}</strong><span>{isAdmin?'cuentas activas':'archivos recibidos'}</span></div></div></div>
  <section className="records-panel"><div className="list-toolbar"><div className="search-box"><Search size={18}/><Input aria-label="Buscar personas por nombre o correo" placeholder="Buscar una persona…" value={query} onChange={e=>onQuery(e.target.value)}/>{query&&<button onClick={()=>onQuery('')} aria-label="Borrar búsqueda"><X size={14}/></button>}</div><Choice id="group-filter" label="Grupo" value={groupFilter} onChange={onGroupFilter} options={[["all","Todos mis grupos"],...groups.map(g=>[g.id,g.name])]}/></div><div className="table-caption"><span>{filtered.length} {filtered.length===1?'persona':'personas'}</span><span>{isAdmin?'Asignación única':'Acceso limitado a tus grupos'}</span></div>
  {filtered.length?<Table><TableHeader><TableRow><TableHead>Persona</TableHead><TableHead>Grupo e itinerario</TableHead><TableHead>{isAdmin?'Parroquia':'Documentación'}</TableHead><TableHead className="text-right"><span className="sr-only">Acciones</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(p=><TableRow key={p.id}><TableCell><button className="person-link" onClick={()=>isAdmin?onModal({kind:'assign',person:p}):onOpen(p)}>{!isAdmin&&<Avatar person={p}/>}<span><strong>{p.firstName} {p.lastName}</strong><small>{isAdmin?'Ficha mínima':p.data?.email||'Correo sin indicar'}</small></span></button></TableCell><TableCell><div className="group-label"><span className={`itinerary-dot ${findGroup(p.groupId)?.itinerary}`}/><div><strong>{findGroup(p.groupId)?.name}</strong><small>{findGroup(p.groupId)?.day} · {findGroup(p.groupId)?.startTime}</small></div></div></TableCell><TableCell>{isAdmin?<span className="muted">{findGroup(p.groupId)?.parish}</span>:<div className="document-status"><Badge variant="outline" className={p.documents?.length?'received':'waiting'}>{p.documents?.length?<><FileText size={13}/>{p.documents.length} {p.documents.length===1?'archivo':'archivos'}</>:<>Sin adjuntos</>}</Badge>{!p.photoId&&<small>Foto sin incorporar</small>}</div>}</TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" onClick={()=>isAdmin?onModal({kind:'assign',person:p}):onOpen(p)}>{isAdmin?'Asignar':'Ver ficha'}<ArrowUpRight size={15}/></Button></TableCell></TableRow>)}</TableBody></Table>:<NoResults title={people.length?'No hay coincidencias':'Todavía no tienes personas asignadas'} description={people.length?'Prueba otro nombre o cambia el grupo seleccionado.':'Administración puede incorporar personas y asignarte a sus grupos.'}/>}</section><p className="bottom-note"><LockKeyhole size={14}/>Los documentos recibidos no se consideran validados automáticamente.</p></>;
}

function GroupsView({groups,isAdmin,onModal,onPeople}){
  return <><div className="page-heading"><div><p className="eyebrow">ORGANIZACIÓN</p><h1>{isAdmin?'Grupos de catequesis':'Mis grupos'}</h1><p>Parroquia, día y horario. Un lugar compartido por sus catequistas.</p></div>{isAdmin&&<Button onClick={()=>onModal({kind:'group'})}><Plus size={16}/>Nuevo grupo</Button>}</div><div className="groups-grid">{groups.map(g=><article key={g.id} className="group-card"><div className="group-card-top"><span className={`itinerary-dot ${g.itinerary}`}/><Badge variant="outline">{g.itinerary==='confirmation'?'1 año':g.itinerary==='baptism-1'?'1.º de 2 años':'2.º de 2 años'}</Badge></div><h2>{g.name}</h2><p className="muted">{itineraries[g.itinerary]}</p><div className="group-details"><p><MapPin size={16}/>{g.parish}</p><p><Clock3 size={16}/>{g.day} · {g.startTime}–{g.endTime}</p></div><div className="group-card-bottom"><div><small>CATEQUISTAS</small><p>{g.catechists.map(u=>u.name.split(' · ')[0]).join(' · ')||'Sin asignar'}</p></div><strong>{g.count}<small>personas</small></strong></div><div className="group-card-actions"><Button variant="ghost" onClick={()=>onPeople(g.id)}>Ver personas<ArrowUpRight size={15}/></Button>{isAdmin&&<Button variant="outline" size="sm" onClick={()=>onModal({kind:'group',group:g})}><Pencil size={14}/>Editar</Button>}</div></article>)}</div>{!groups.length&&<NoResults title="Sin grupos asignados" description="Administración debe definir tu ámbito. No se concede acceso global automáticamente."/>}</>;
}
function PersonDetail({person:p,group:g,canEdit,onBack,onModal}) {
  return <><Button variant="ghost" className="back-link" onClick={onBack}><ArrowLeft size={16}/>Volver a personas</Button><section className="person-hero"><Avatar person={p} large/><div className="person-heading"><p className="eyebrow">FICHA PERSONAL</p><h1>{p.firstName} {p.lastName}</h1><div className="person-subline"><span className={`itinerary-dot ${g?.itinerary}`}/>{g?.name}<span>·</span>{g?.parish}</div></div><div className="heading-actions">{canEdit?<><Button variant="outline" onClick={()=>onModal({kind:'photo',person:p})}><Camera size={16}/>{p.photoId?'Cambiar foto':'Subir foto'}</Button><Button onClick={()=>onModal({kind:'person',person:p})}><Pencil size={16}/>Editar ficha</Button></>:<Badge variant="outline"><LockKeyhole size={14}/>Solo consulta</Badge>}</div></section>
  <Tabs defaultValue="personal" className="profile-tabs"><TabsList variant="line"><TabsTrigger value="personal">Datos personales</TabsTrigger><TabsTrigger value="sacraments">Sacramentos y familia</TabsTrigger><TabsTrigger value="documents">Documentación <span className="tab-count">{p.documents?.length??0}</span></TabsTrigger></TabsList>
  <TabsContent value="personal"><div className="detail-grid"><section className="detail-card"><h2>Información personal</h2><dl className="facts-grid"><Fact label="Nombre">{p.firstName}</Fact><Fact label="Apellidos">{p.lastName}</Fact><Fact label="Fecha de nacimiento">{date(p.data?.birthDate)}</Fact><Fact label="Lugar de nacimiento">{p.data?.birthPlace}</Fact><Fact label="Teléfono">{p.data?.phone}</Fact><Fact label="Correo electrónico">{p.data?.email}</Fact></dl><h3>Domicilio</h3><dl className="facts-grid"><Fact label="Dirección">{p.data?.address}</Fact><Fact label="Localidad">{p.data?.city}</Fact><Fact label="Provincia">{p.data?.province}</Fact><Fact label="Código postal">{p.data?.postalCode}</Fact><Fact label="País">{p.data?.country}</Fact></dl></section><aside className="detail-aside"><section className="group-summary"><p className="eyebrow">SU GRUPO</p><h2>{g?.name}</h2><p><MapPin size={17}/>{g?.parish}</p><p><Clock3 size={17}/>{g?.day} · {g?.startTime}–{g?.endTime}</p><div className="group-staff"><small>CATEQUISTAS</small>{g?.catechists.map(u=><span key={u.id}>{u.name.split(' · ')[0]}</span>)}</div></section><div className="quiet-note"><Info size={18}/><p>Una casilla sin información significa «sin indicar», no una respuesta negativa.</p></div><p className="muted text-xs">Último cambio: {date(p.updatedAt)}</p></aside></div></TabsContent>
  <TabsContent value="sacraments"><section className="detail-card"><h2>Situación sacramental</h2><div className="sacrament-row">{[['baptism','Bautismo'],['communion','Primera comunión'],['confirmation','Confirmación']].map(([key,label])=><div key={key} className="sacrament-item"><span>{label}</span><Badge variant="outline" className={p.data?.[key]==='yes'?'received':'waiting'}>{statuses[p.data?.[key]??'unknown']}</Badge></div>)}</div><h2>Padrinos y madrinas</h2><dl className="facts-grid"><Fact label="De bautismo">{p.data?.baptismSponsor}</Fact><Fact label="De confirmación">{p.data?.confirmationSponsor}</Fact></dl><h2>Datos familiares</h2><p className="muted">Campos de referencia de la ficha, especialmente para personas no bautizadas. Consulta la información disponible según cada caso.</p><dl className="facts-grid">{family.map(([key,label])=><Fact key={key} label={label}>{p.data?.[key]}{p.data?.[`${key}Birth`]&&<small className="block muted">Lugar de nacimiento: {p.data[`${key}Birth`]}</small>}</Fact>)}</dl></section></TabsContent>
  <TabsContent value="documents"><section className="detail-card"><div className="section-heading"><div><h2>Documentos recibidos</h2><p className="muted">Archivos del participante y de sus padrinos, identificados por separado.</p></div>{canEdit&&<Button onClick={()=>onModal({kind:'document',person:p})}><Upload size={16}/>Adjuntar documento</Button>}</div>{p.documents?.length?<div className="file-list">{p.documents.map(f=><article className="file-row" key={f.id}><span className="file-icon"><FileText size={23}/></span><div><h3>{docNames[f.type]??f.type}</h3><p>{f.ownerName} <span>·</span> {f.owner==='participant'?'Participante':'Padrino / madrina'}</p><small>{f.name} · {(f.size/1024).toFixed(0)} KB · {date(f.createdAt)}</small></div><Button variant="outline" asChild><a href={`/api/files/${f.id}`} target="_blank" rel="noopener noreferrer">Consultar<ArrowUpRight size={15}/></a></Button></article>)}</div>:<NoResults title="Todavía no hay documentos" description="Se incorporarán cuando estén disponibles. No es necesario tenerlos todos para consultar la ficha."/>}<div className="quiet-note"><Info size={17}/><p>«Recibido» no significa «validado». Todavía no se aplica una lista obligatoria por sacramento ni se declara un expediente completo.</p></div></section></TabsContent></Tabs></>;
}

function Guide(){return <div className="guide"><div className="page-heading"><div><p className="eyebrow">DOCUMENTACIÓN · VERSIÓN 0.1</p><h1>Una primera versión para comentar</h1><p>El objetivo es probar el trabajo diario, no dar por cerrado el diseño.</p></div><Badge variant="outline">28 AGO 2026</Badge></div><section className="detail-card"><h2>Un recorrido de cinco minutos</h2><ol className="guide-steps"><li><strong>Entra como Ana.</strong> Consulta personas de confirmación y primero; las de segundo no aparecerán.</li><li><strong>Abre una ficha.</strong> Completa un dato, guarda y vuelve a abrirla. Los cambios se conservan en este ordenador.</li><li><strong>Prueba los adjuntos.</strong> Sube una foto JPG/PNG y un PDF ficticio; comprueba quién es el titular.</li><li><strong>Entra como «consulta».</strong> Solo verá confirmación y no podrá modificar nada.</li><li><strong>Entra como administración.</strong> Revisa usuarios, grupos y asignaciones; no tendrás acceso a fotos o documentos.</li></ol></section><div className="guide-grid"><section className="detail-card"><h2>Qué funciona</h2><ul><li>Sesiones y tres perfiles con permisos en servidor.</li><li>Fichas, datos sacramentales, familiares y padrinos.</li><li>Grupos con varios catequistas y pertenencia única.</li><li>Fotos de hasta 2 MB; documentos PDF/JPG/PNG de hasta 5 MB.</li><li>Datos y archivos guardados en SQLite local.</li><li>Detección de cambios simultáneos y archivos duplicados.</li></ul></section><section className="detail-card"><h2>Organización actual</h2><ul><li>Administración crea fichas mínimas: nombre, apellidos y grupo.</li><li>El resto de los datos los completa el catequista asignado.</li><li>El arzobispado consulta solo grupos expresamente asignados.</li><li>Se permiten datos incompletos y estados «sin comprobar».</li><li>Primero y segundo se representan como grupos separados.</li></ul><p className="muted">Esta es la organización configurada para la demostración.</p></section></div><section className="feedback-prompt"><BookOpen size={24}/><div><h2>¿Qué te resulta natural y qué cambiarías?</h2><p>Puedes comentar la ficha, los grupos o los permisos por separado. No hace falta cerrar todo a la vez.</p></div></section></div>;}

function EditModal({modal,groups,users,api,onClose,onSaved}) {
  const {person,group,user,kind}=modal;
  const [firstName,setFirst]=useState(person?.firstName??''),[lastName,setLast]=useState(person?.lastName??'');
  const [data,setData]=useState(person?.data??{});
  const [groupId,setGroupId]=useState(person?.groupId??groups[0]?.id??'');
  const [name,setName]=useState(group?.name??user?.name??''),[parish,setParish]=useState(group?.parish??'');
  const [day,setDay]=useState(group?.day??'Miércoles'),[startTime,setStart]=useState(group?.startTime??'19:00'),[endTime,setEnd]=useState(group?.endTime??'20:00'),[itinerary,setItinerary]=useState(group?.itinerary??'confirmation');
  const [chosenIds,setChosenIds]=useState(group?.catechists.map(u=>u.id)??user?.groupIds??[]);
  const [username,setUsername]=useState(user?.username??''),[role,setRole]=useState(user?.role??'catechist'),[active,setActive]=useState(user?.active??true),[password,setPassword]=useState('');
  const [docType,setDocType]=useState('birth'),[owner,setOwner]=useState('participant'),[file,setFile]=useState(null),[preview,setPreview]=useState('');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[duplicate,setDuplicate]=useState(false);
  useEffect(()=>{if(!file||!file.type.startsWith('image/')){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  const toggle=(id,checked)=>setChosenIds(prev=>checked?[...new Set([...prev,id])]:prev.filter(v=>v!==id));
  const update=(key,value)=>setData(prev=>({...prev,[key]:value}));
  function chooseFile(f){setError('');if(f&&f.size>(kind==='photo'?2:5)*1024*1024){setError(`El archivo supera los ${kind==='photo'?2:5} MB permitidos.`);setFile(null);return;}setFile(f);}
  async function submit(event){
    event.preventDefault();setBusy(true);setError('');
    try{
      if(kind==='person') {
        if(person)await api(`/api/people/${person.id}`,'PUT',{firstName,lastName,data,version:person.version});
        else await api('/api/people','POST',{firstName,lastName,groupId,allowDuplicate:duplicate});
      } else if(kind==='assign')await api(`/api/people/${person.id}/group`,'PUT',{groupId,version:person.version});
      else if(kind==='group')await api(group?`/api/groups/${group.id}`:'/api/groups',group?'PUT':'POST',{name,parish,day,startTime,endTime,itinerary,catechistIds:chosenIds,...(group?{version:group.version}:{})});
      else if(kind==='user')await api(user?`/api/users/${user.id}`:'/api/users',user?'PUT':'POST',{name,username,role,active,password,groupIds:role==='admin'?[]:chosenIds,...(user?{version:user.version}:{})});
      else {
        if(!file)throw new Error('Selecciona un archivo antes de continuar.');
        const base64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=()=>no(new Error('No se ha podido leer el archivo.'));r.readAsDataURL(file);});
        await api(`/api/people/${person.id}/${kind==='photo'?'photo':'documents'}`,'POST',{name:file.name,base64,version:person.version,...(kind==='document'?{type:docType,owner}:{})});
      }
      await onSaved();
    }catch(e){setError(e.message);}finally{setBusy(false);}
  }
  const title=kind==='person'?(person?'Editar ficha':'Nueva ficha mínima'):kind==='assign'?'Asignar grupo':kind==='group'?(group?'Editar grupo':'Nuevo grupo'):kind==='user'?(user?'Editar usuario':'Nuevo usuario'):kind==='photo'?'Foto de la ficha':'Adjuntar documento';
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className={`edit-dialog ${kind==='person'&&person?'wide':''}`} showCloseButton={false} onPointerDownOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{if(busy)e.preventDefault();}}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{person?`${person.firstName} ${person.lastName}`:kind==='group'?'Datos compartidos por todos los integrantes del grupo.':kind==='user'?'Cada cuenta tiene un único perfil y un ámbito explícito.':'El catequista completará los datos personales.'}</DialogDescription></DialogHeader><DialogClose asChild><Button variant="ghost" size="icon" className="dialog-close" disabled={busy} aria-label="Cerrar formulario"><X size={18}/></Button></DialogClose><form onSubmit={submit} className="edit-form"><div className="form-scroll">
  {kind==='person'&&<><div className="form-grid"><div className="field"><Label htmlFor="firstName">Nombre *</Label><Input id="firstName" required maxLength={100} value={firstName} onChange={e=>setFirst(e.target.value)}/></div><div className="field"><Label htmlFor="lastName">Apellidos *</Label><Input id="lastName" required maxLength={160} value={lastName} onChange={e=>setLast(e.target.value)}/></div></div>{!person?<><Choice id="person-group" label="Grupo *" value={groupId} onChange={setGroupId} options={groups.map(g=>[g.id,g.name])}/><p className="form-note">Se creará una ficha sin foto, documentos ni sacramentos supuestos. El catequista completará después el resto de la ficha.</p><label className="checkline"><Checkbox checked={duplicate} onCheckedChange={v=>setDuplicate(v===true)}/>He revisado una posible coincidencia de nombre y confirmo que es otra persona.</label></>:<Tabs defaultValue="basic"><TabsList><TabsTrigger value="basic">Datos</TabsTrigger><TabsTrigger value="sacramental">Sacramentos</TabsTrigger><TabsTrigger value="family">Familia</TabsTrigger></TabsList><TabsContent value="basic"><div className="form-grid">{fields.map(([key,label,type])=><div className="field" key={key}><Label htmlFor={`f-${key}`}>{label}</Label><Input id={`f-${key}`} type={type??'text'} maxLength={key==='address'?300:160} value={data[key]??''} onChange={e=>update(key,e.target.value)}/></div>)}</div></TabsContent><TabsContent value="sacramental"><div className="form-grid">{[['baptism','Bautismo'],['communion','Primera comunión'],['confirmation','Confirmación']].map(([key,label])=><Choice id={`s-${key}`} key={key} label={label} value={data[key]??'unknown'} onChange={v=>update(key,v)} options={Object.entries(statuses)}/>)}</div><h3>Padrinos y madrinas</h3>{[['baptismSponsor','De bautismo'],['confirmationSponsor','De confirmación']].map(([key,label])=><div className="field" key={key}><Label htmlFor={key}>{label}: nombre y apellidos</Label><Input id={key} maxLength={160} value={data[key]??''} onChange={e=>update(key,e.target.value)}/></div>)}<p className="form-note">Si un padrino ya tiene certificados, no se permite sustituirlo hasta definir cómo conservar su historial.</p></TabsContent><TabsContent value="family"><p className="form-note">Completa solo la información disponible y pertinente. Los campos no son obligatorios en esta revisión.</p><div className="form-grid">{family.map(([key,label])=><div key={key} className="family-field"><Label htmlFor={`family-${key}`}>{label}</Label><Input id={`family-${key}`} aria-label={`${label}: nombre y apellidos`} placeholder="Nombre y apellidos" maxLength={160} value={data[key]??''} onChange={e=>update(key,e.target.value)}/><Input aria-label={`${label}: lugar de nacimiento`} placeholder="Lugar de nacimiento" maxLength={160} value={data[`${key}Birth`]??''} onChange={e=>update(`${key}Birth`,e.target.value)}/></div>)}</div></TabsContent></Tabs>}</>}
  {kind==='assign'&&<><Choice id="assignment-group" label="Grupo de destino" value={groupId} onChange={setGroupId} options={groups.map(g=>[g.id,g.name])}/><div className="quiet-note"><Info size={18}/><p>Al guardar, la persona dejará su grupo anterior. Sus datos y archivos pasarán al ámbito de los catequistas del nuevo grupo.</p></div><p className="form-note">{groups.find(g=>g.id===groupId)?.parish} · {groups.find(g=>g.id===groupId)?.day} · {groups.find(g=>g.id===groupId)?.startTime}</p></>}
  {kind==='group'&&<><div className="field"><Label htmlFor="group-name">Nombre del grupo *</Label><Input id="group-name" required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><Label htmlFor="parish">Parroquia *</Label><Input id="parish" required maxLength={160} value={parish} onChange={e=>setParish(e.target.value)}/></div><Choice id="itinerary" label="Itinerario / nivel" value={itinerary} onChange={setItinerary} options={Object.entries(itineraries)}/><Choice id="day" label="Día" value={day} onChange={setDay} options={['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map(d=>[d,d])}/><div className="form-grid"><div className="field"><Label htmlFor="start">Desde</Label><Input id="start" required type="time" value={startTime} onChange={e=>setStart(e.target.value)}/></div><div className="field"><Label htmlFor="end">Hasta</Label><Input id="end" required type="time" value={endTime} onChange={e=>setEnd(e.target.value)}/></div></div><fieldset><legend>Catequistas asignados</legend>{users.filter(u=>u.role==='catechist'&&u.active).map(u=><label className="checkline" key={u.id}><Checkbox checked={chosenIds.includes(u.id)} onCheckedChange={v=>toggle(u.id,v===true)}/>{u.name}</label>)}</fieldset></>}
  {kind==='user'&&<><div className="field"><Label htmlFor="user-name">Nombre visible *</Label><Input id="user-name" required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><Label htmlFor="user-login">Usuario de acceso *</Label><Input id="user-login" required minLength={3} maxLength={80} autoComplete="off" value={username} onChange={e=>setUsername(e.target.value)}/></div><Choice id="role" label="Perfil" value={role} onChange={v=>{setRole(v);setChosenIds([]);}} options={Object.entries(roleNames)}/><div className="field"><Label htmlFor="new-password">{user?'Nueva contraseña (dejar vacía para conservar)':'Contraseña inicial *'}</Label><Input id="new-password" type="password" autoComplete="new-password" required={!user} minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></div><label className="checkline"><Checkbox checked={active} onCheckedChange={v=>setActive(v===true)}/>Cuenta activa</label>{role!=='admin'&&<fieldset><legend>{role==='reader'?'Grupos que podrá consultar':'Grupos que podrá gestionar'}</legend>{groups.map(g=><label className="checkline" key={g.id}><Checkbox checked={chosenIds.includes(g.id)} onCheckedChange={v=>toggle(g.id,v===true)}/>{g.name}</label>)}<p className="form-note">Sin selección, no tendrá acceso a ninguna ficha.</p></fieldset>}<p className="form-note">Cambiar el perfil, desactivar la cuenta o cambiar la contraseña cierra sus sesiones actuales.</p></>}
  {(kind==='photo'||kind==='document')&&<>{kind==='document'&&<><Choice id="doc-type" label="Tipo de documento" value={docType} onChange={v=>{setDocType(v);setOwner(v==='sponsor-confirmation'?'confirmationSponsor':'participant');}} options={Object.entries(docNames)}/><Choice id="doc-owner" label="Titular del documento" value={owner} onChange={setOwner} options={docType==='sponsor-confirmation'?[['baptismSponsor',`Padrino de bautismo · ${person?.data?.baptismSponsor||'sin indicar'}`],['confirmationSponsor',`Padrino de confirmación · ${person?.data?.confirmationSponsor||'sin indicar'}`]]:[['participant',`${person?.firstName} ${person?.lastName}`]]}/></>}<div className="upload-zone"><Upload size={28}/><Label htmlFor="file-picker">{kind==='photo'?'Selecciona una foto de prueba':'Selecciona un documento de prueba'}</Label><p>{kind==='photo'?'JPG o PNG · hasta 2 MB':'PDF, JPG o PNG · hasta 5 MB'}</p><Input id="file-picker" type="file" accept={kind==='photo'?'.jpg,.jpeg,.png':'.pdf,.jpg,.jpeg,.png'} onChange={e=>chooseFile(e.target.files?.[0]??null)}/></div>{file&&<div className="file-preview">{preview&&<img src={preview} alt="Vista previa del archivo seleccionado"/>}<strong>{file.name}</strong><small>{(file.size/1024).toFixed(0)} KB · {person?.firstName} {person?.lastName}</small></div>}<p className="form-note">{kind==='photo'&&person?.photoId?'La nueva foto se mostrará al confirmar. La anterior se conserva internamente; esta versión no incluye gestión del historial.':'Comprueba el titular antes de guardar. No se valida la autenticidad del documento.'}</p></>}
  {error&&<div className="error-box" role="alert">{error}</div>}</div><div className="form-footer"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy||((kind==='photo'||kind==='document')&&!file)}>{busy?'Guardando…':kind==='photo'?'Confirmar foto':kind==='document'?'Guardar documento':'Guardar cambios'}{!busy&&<Check size={16}/>}</Button></div></form></DialogContent></Dialog>;
}

function UsersView({users,groups,onModal}){
  return <><div className="page-heading"><div><p className="eyebrow">ADMINISTRACIÓN DEL SISTEMA</p><h1>Usuarios y permisos</h1><p>Cuentas individuales y acceso explícito a los grupos.</p></div><Button onClick={()=>onModal({kind:'user'})}><Plus size={16}/>Nuevo usuario</Button></div><section className="records-panel"><Table><TableHeader><TableRow><TableHead>Usuario</TableHead><TableHead>Perfil</TableHead><TableHead>Ámbito</TableHead><TableHead>Estado</TableHead><TableHead><span className="sr-only">Acción</span></TableHead></TableRow></TableHeader><TableBody>{users.map(u=><TableRow key={u.id}><TableCell><strong className="block">{u.name}</strong><small className="muted">{u.username}</small></TableCell><TableCell>{roleNames[u.role]}</TableCell><TableCell>{u.role==='admin'?'Organización, sin acceso a archivos':u.groupIds.map(id=>groups.find(g=>g.id===id)?.name).join(' · ')||'Sin grupos'}</TableCell><TableCell><Badge variant="outline" className={u.active?'received':'waiting'}>{u.active?'Activo':'Inactivo'}</Badge></TableCell><TableCell><Button variant="ghost" size="sm" onClick={()=>onModal({kind:'user',user:u})}><Pencil size={14}/>Editar</Button></TableCell></TableRow>)}</TableBody></Table></section><div className="quiet-note"><ShieldCheck size={18}/><p>El perfil de consulta no puede modificar fichas ni archivos. Desactivar una cuenta retira su acceso, pero no borra información.</p></div></>;
}
